### ISSUE TITLE
Suggestion: Allow multiple searches

### ISSUE THREAD

**Issue by Glaived** [AcelisWeaven/AbyssExplorer#14]
![image](https://user-images.githubusercontent.com/1835170/97993824-df3d0800-1de4-11eb-8a5a-57ae8eaf6769.png)

**Comment by AcelisWeaven** [comment]
Hi @Glaived, it should already be possible using a comma, like this:
![image](https://user-images.githubusercontent.com/6735195/97995933-73a86a00-1de7-11eb-9b12-37900f3f3cef.png)

Let me know if this fixes your issue!

**Comment by Glaived** [comment]
I modified [my mod of Neon Abyss Explorer](https://gist.github.com/Glaived/bf80a268fdbc5ed8ffd71e7786c8cfa6) to take into consideration the + as a comma.

I prefer the + but the comma is no less bad for it
