### ISSUE TITLE
Suggestion: Lidless Eye - description too unclear

### ISSUE THREAD

**Issue by Glaived** [AcelisWeaven/AbyssExplorer#16]
![image](https://user-images.githubusercontent.com/1835170/98104588-ea507080-1e96-11eb-8658-9e7781c73b2e.png)

Replace
> It sees ...... EVERYTHING! Including your inner desires and fears.

By
> It sees ...... EVERYTHING! Including your inner desires and fears. Maps are revealed in every level.

**Comment by AcelisWeaven** [comment]
Thanks for the suggestion!
I'd like to avoid changing the items descriptions, the current descriptions are taken directly from the game so it would be overridden with each update. Also, it's hard to keep track of the changes over time.

I've though about this before and I think a good system would be to have a file of additional information (which can be easily contributed to)
The file would look like this:
```json
{
  // ...
  "lidless-eye": {
    "en": "Maps are revealed in every level.",
    "fr": "Dévoile entièrement la carte.",
    "cn": "...",
    "ru": "...",
  }
  // ...
}
```

**Comment by Glaived** [comment]
I think it's a good idea

**Comment by AcelisWeaven** [comment]
I've added the support of additional descriptions. Thanks @Glaived !
Feel free to reopen if anything's wrong of course 😉
