### ISSUE TITLE
Suggestion - More display modes

### ISSUE THREAD

**Issue by Glaived** [AcelisWeaven/AbyssExplorer#2]
### Dual (Example) :

| image1 | description1 | image2 | description2 |
| --- | --- | --- | --- |
| image3 | description3 | image4 | description4 |
| image5 | description5 | image6 | description6 |

### Tooltip :
![image](https://user-images.githubusercontent.com/1835170/87844677-c8b78300-c8bf-11ea-80b7-88cfeac1b241.png)
Example from https://minecraftdungeons.gg/gear/melee

**Comment by AcelisWeaven** [comment]
Thanks for this other suggestion!
Just posting to tell you that I'm working on this too, a Reddit user also suggested a condensed view [like in this Isaac tool](https://platinumgod.co.uk/).

**Comment by AcelisWeaven** [comment]
And it's done! Thanks again for the suggestions.
