### ISSUE TITLE
import './generated/spritesheet.css' not found

### ISSUE THREAD

**Issue by Glaived** [AcelisWeaven/AbyssExplorer#21]
https://github.com/AcelisWeaven/AbyssExplorer/blob/342a56e23f9fb1e92200be1a58396f43957b5c4c/src/main.js#L6

because

https://github.com/AcelisWeaven/AbyssExplorer/blob/342a56e23f9fb1e92200be1a58396f43957b5c4c/.gitignore#L25

from

https://github.com/AcelisWeaven/AbyssExplorer/commit/95e2cadef526d45941dd08a2364c6c88d9fea9b8#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947

**Comment by aaroncameron21** [comment]
Ran into this as well. For me it was an error appearing due to a .replaceAll() call in vue.config.js. 
replaceAll() was added in node v15, and I was running v14.*. I took the chance to upgrade to 15, should solve it for you as well assuming the root cause is the same.

**Comment by AcelisWeaven** [comment]
Thanks @aaroncameron21 for investigating, I couldn't figure this one out.

I'm on vacation and I have some free time, I'll take the time to merge your PRs, sorry for the wait.

@Glaived Would you mind updating Node and telling us if it solves the issue? Also, when was your issue happening?

**Comment by AcelisWeaven** [comment]
Regarding the `replaceAll()` issue, I've replaced it with a more supported `replace()`, this should have fixed this issue.
I also took the time to add some continuous integration, so future PRs will be deployed more easily.

**Comment by Glaived** [comment]
> Ran into this as well. For me it was an error appearing due to a .replaceAll() call in vue.config.js.
replaceAll() was added in node v15, and I was running v14.*. I took the chance to upgrade to 15, should solve it for you as well assuming the root cause is the same.

The problem came from the version of Node.

> Regarding the `replaceAll()` issue, I've replaced it with a more supported `replace()`, this should have fixed this issue.
> I also took the time to add some continuous integration, so future PRs will be deployed more easily.

@AcelisWeaven I don't think it's problematic to use node 15 and replaceAll(), on the other hand, it might be interesting to specify this pre-requirement in the project https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines and add by hand the necessary versions for volta users https://docs.volta.sh/guide/understanding#managing-your-project

In view of the initial problem of the issue, being resolved, I close
