### ISSUE TITLE
AbyssExplorer must be updated to version 1.25

### ISSUE THREAD

**Issue by Glaived** [AcelisWeaven/AbyssExplorer#23]
[Patch 1.25](https://steamcommunity.com/games/788100/announcements/detail/2945882680469618681)

**Comment by AcelisWeaven** [comment]
I spent the day working on this patch, but I'm having some issues with datamining, so I don't know how much time it will take. Will keep you posted!

**Comment by AcelisWeaven** [comment]
Updated! Feel free to reopen if you think something is missing.
