### ISSUE TITLE
Missing weapon

### ISSUE THREAD

**Issue by Glaived** [AcelisWeaven/AbyssExplorer#3]
![image](https://user-images.githubusercontent.com/1835170/87866069-1645f580-c97d-11ea-8c6a-3d2b404caa3c.png)

**Comment by AcelisWeaven** [comment]
Hi @Glaived , do you have its name by any chance?

**Comment by AcelisWeaven** [comment]
Fixed! There was a total of 11 missing weapons. I missed them because they have a different filename than their id.
