### ISSUE TITLE
Suggestion - Sort by colors

### ISSUE THREAD

**Issue by draciel64** [AcelisWeaven/AbyssExplorer#7]
I do like the new rearrangement of the items but I would suggest maybe color coordinating the items for easier identification?

**Comment by AcelisWeaven** [comment]
Hi, thanks for the suggestion! You're not the first one to ask this feature, so I'll probably add it.

Just a question: would it be really easier to find items by color? In a game like The Binding of Isaac, items names were not shown so you had to rely on stuff like shape, color... But in Neon Abyss, item names are shown before you pick them up and should be quick to search. What's your opinion @draciel64 ?

**Comment by draciel64** [comment]
On the older format (the one you had to scroll down) I did use the search bar more often but now that everything is on one screen I'd think it would be easier to look for the matching item rather than type it out. Especially when shop items do not show their names. Thanks for the consideration, maybe I'm an outlier since I have two monitors to compare and search.

**Comment by AcelisWeaven** [comment]
Ah I think I got it, they added the names in the shop in the experimental version and that's why I didn't see it.

Stable:
![image](https://user-images.githubusercontent.com/6735195/87950600-cd3e9000-caa7-11ea-80d5-44eb88dfa96f.png)

Experimental:
![image](https://user-images.githubusercontent.com/6735195/87950863-25759200-caa8-11ea-99b3-32290232768c.png)

> maybe I'm an outlier since I have two monitors to compare and search
Don't worry, that's what I do too! I'll try to add this feature soon.

**Comment by Glaived** [comment]
if at the next update, the names are available everywhere, I don't think it's an interesting feature. It will always be slower than the search function.

**Comment by AcelisWeaven** [comment]
@draciel64 I've added an option to sort by colors.
For the moment, the colors were automatically picked and manual adjustments is needed (thus, I'll leave this ticket open for now :) )

@Glaived I'll reconsider the feature when the update is deployed everywhere, but it's true that when you have two screens (one with Abyss Explorer, the other with Neon Abyss) color sorting could help a little as the only input needed are alt-tab/click/alt-tab.

I don't have a strong opinion in favor or against this feature, but if it can help a single person then that's great.

**Comment by draciel64** [comment]
This is great. I am going to switch over to experimental after defeating Athena so I'll probably use the search function more often eventually. In the meantime, thanks for being so accommodating for leaving option preferences.

**Comment by AcelisWeaven** [comment]
Hi @draciel64, I've updated the app with a better color sorting (by hand!)
It should also help console players, since they're a few weeks away from the "labelled items" update.

I'll close the issue now, but if you see anything wrong please reopen it. Thanks for the suggestion!
